name: "Send To Discord"
author: "hugoalh"
description: "Send message to Discord via webhook, support variables."
inputs:
  discord_webhook_url:
    description: "[Secret String] Discord webhook url."
    required: true
  discord_webhook_name:
    description: "[String 2 ~ 32 charactors] Discord webhook display name (i.e.: the sender's name)."
    required: false
  discord_webhook_avatarurl:
    description: "[String] Discord webhook avatar url."
    required: false
  message_tts:
    description: "[Stringified Boolean] Text to speech (TTS)."
    required: false
    default: "false"
  message_text:
    description: "[String <= 2000 charactors] Text message."
    required: false
  message_embed_colour:
    description: "[String] Colour that display at the left border of the embed message; in `RANDOM`, `INVISIBLE`, 6-digit RGB hex with prefix `#`, or decimal."
    required: false
    default: "INVISIBLE"
  message_embed_author_name:
    description: "[String 2 ~ 32 charactors] Author name of the embed message."
    required: false
  message_embed_author_url:
    description: "[String] Url on the author name of the embed message."
    required: false
  message_embed_author_avatarurl:
    description: "[String] Author avatar url of the embed message."
    required: false
  message_embed_title:
    description: "[String <= 256 charactors] Embed message title."
    required: false
  message_embed_titleurl:
    description: "[String] Url on the title of the embed message, required \"message_embed_title\"."
    required: false
  message_embed_description:
    description: "[String <= 2048 charactors] Embed message description."
    required: false
  message_embed_thumbnailurl:
    description: "[String] Embed message thumbnail."
    required: false
  message_embed_imageurl:
    description: "[String] Embed message image url."
    required: false
  message_embed_videourl:
    description: "[String] Embed message video url."
    required: false
  message_embed_fields:
    description: "[Stringified Magic Array] Embed message fields."
    required: false
  message_embed_footer_iconurl:
    description: "[String] Embed message footer icon url, required \"message_embed_footer_text\"."
    required: false
  message_embed_footer_text:
    description: "[String <= 2048 charactors] Embed message footer text."
    required: false
  message_variables_list:
    description: "[Stringified JSON] Variables list that use in the message content. Can import data from \"Release Fetcher\" or other places."
    required: false
  message_variables_prefix:
    description: "[String] Prefix of the variables."
    required: false
    default: "%"
  message_variables_suffix:
    description: "[String] Suffix of the variables."
    required: false
    default: "%"
  message_variables_join:
    description: "[String] Join of the variables if the variables list has depth."
    required: false
    default: "."
runs:
  using: "node12"
  main: "main.js"
branding:
  icon: "send"
  color: "blue"
