name: "Send Discord Webhook"
author: "hugoalh"
description: "Send a Discord webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  method:
    description: "{string} Method to send."
    required: false
  payload:
    description: "{object} JSON/YAML/YML payload."
    required: false
    default: "{}"
  files:
    description: "{string[]} Files as attachments."
    required: false
    default: "[]"
  threadid:
    description: "{string} Thread ID; Send to the specified thread within a webhook's channel."
    required: false
  wait:
    description: "{boolean} Whether to wait for Discord confirmation of message send before response."
    required: false
    default: "false"
  truncate_enable:
    description: "{boolean} Whether to try truncate firstly when input `payload` is too large."
    required: false
    default: "true"
  truncate_ellipsis:
    description: "{string} Ellipsis."
    required: false
    default: "..."
  truncate_position:
    description: "{string} Ellipsis position."
    required: false
    default: "end"
runs:
  using: "node16"
  main: "dist/main.js"
branding:
  icon: "send"
  color: "blue"
